# Generated by Django 3.2 on 2021-04-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='compNo',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
