# Generated by Django 3.2 on 2021-04-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_complaint_compno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billno', models.CharField(max_length=10)),
                ('amount', models.CharField(max_length=10)),
                ('issuedate', models.DateField()),
                ('paiddate', models.DateField()),
                ('appartment', models.CharField(max_length=10)),
                ('ownerid', models.CharField(max_length=10)),
            ],
        ),
    ]
