# Generated by Django 3.2 on 2021-04-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_complaint_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='Status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
