# Generated by Django 3.2 on 2021-04-29 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_bills_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bills',
            name='ownerid',
        ),
        migrations.AddField(
            model_name='bills',
            name='username1',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
